# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/wlayout.ui'
#
# Created: Tue Apr  5 12:02:37 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

import os
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(515, 475)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(515, 475))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.verticalLayout_1 = QtGui.QVBoxLayout(self.tab_1)
        self.verticalLayout_1.setObjectName(_fromUtf8("verticalLayout_1"))
        self.textEdit = QtGui.QTextEdit(self.tab_1)
        self.textEdit.setAutoFillBackground(True)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_1.addWidget(self.textEdit)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(os.path.realpath(__file__)), "../ico/tab_status.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_1, icon, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.treeWidget = QtGui.QTreeWidget(self.tab_2)
        self.treeWidget.setColumnCount(2)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.header().setDefaultSectionSize(240)
        self.verticalLayout_2.addWidget(self.treeWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(os.path.realpath(__file__)), "../ico/tab_folders.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon1, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_1 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_1.setObjectName(_fromUtf8("groupBox_1"))
        self.horizontalLayout_1 = QtGui.QHBoxLayout(self.groupBox_1)
        self.horizontalLayout_1.setObjectName(_fromUtf8("horizontalLayout_1"))
        self.yandex_exec = QtGui.QLineEdit(self.groupBox_1)
        self.yandex_exec.setObjectName(_fromUtf8("yandex_exec"))
        self.horizontalLayout_1.addWidget(self.yandex_exec)
        self.verticalLayout_3.addWidget(self.groupBox_1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.yandex_cfg = QtGui.QLineEdit(self.groupBox_2)
        self.yandex_cfg.setObjectName(_fromUtf8("yandex_cfg"))
        self.horizontalLayout_2.addWidget(self.yandex_cfg)
        self.ch_yandex_cfg = QtGui.QToolButton(self.groupBox_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(os.path.realpath(__file__)), "../ico/folder_edit.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ch_yandex_cfg.setIcon(icon2)
        self.ch_yandex_cfg.setObjectName(_fromUtf8("ch_yandex_cfg"))
        self.horizontalLayout_2.addWidget(self.ch_yandex_cfg)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.yandex_root = QtGui.QLineEdit(self.groupBox_3)
        self.yandex_root.setObjectName(_fromUtf8("yandex_root"))
        self.horizontalLayout_3.addWidget(self.yandex_root)
        self.ch_yandex_root = QtGui.QToolButton(self.groupBox_3)
        self.ch_yandex_root.setIcon(icon2)
        self.ch_yandex_root.setObjectName(_fromUtf8("ch_yandex_root"))
        self.horizontalLayout_3.addWidget(self.ch_yandex_root)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.yandex_auth = QtGui.QLineEdit(self.groupBox_4)
        self.yandex_auth.setObjectName(_fromUtf8("yandex_auth"))
        self.horizontalLayout_4.addWidget(self.yandex_auth)
        self.ch_yandex_auth = QtGui.QToolButton(self.groupBox_4)
        self.ch_yandex_auth.setIcon(icon2)
        self.ch_yandex_auth.setObjectName(_fromUtf8("ch_yandex_auth"))
        self.horizontalLayout_4.addWidget(self.ch_yandex_auth)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(os.path.realpath(__file__)), "../ico/tab_conf.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.proxyNone = QtGui.QRadioButton(self.groupBox_5)
        self.proxyNone.setObjectName(_fromUtf8("proxyNone"))
        self.verticalLayout_5.addWidget(self.proxyNone)
        self.proxyAuto = QtGui.QRadioButton(self.groupBox_5)
        self.proxyAuto.setChecked(True)
        self.proxyAuto.setObjectName(_fromUtf8("proxyAuto"))
        self.verticalLayout_5.addWidget(self.proxyAuto)
        self.proxyManual = QtGui.QRadioButton(self.groupBox_5)
        self.proxyManual.setObjectName(_fromUtf8("proxyManual"))
        self.verticalLayout_5.addWidget(self.proxyManual)
        self.proxyManualWidget = QtGui.QWidget(self.groupBox_5)
        self.proxyManualWidget.setEnabled(False)
        self.proxyManualWidget.setObjectName(_fromUtf8("proxyManualWidget"))
        self.gridLayout = QtGui.QGridLayout(self.proxyManualWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.srvLogin = QtGui.QLineEdit(self.proxyManualWidget)
        self.srvLogin.setEnabled(False)
        self.srvLogin.setObjectName(_fromUtf8("srvLogin"))
        self.gridLayout.addWidget(self.srvLogin, 4, 2, 1, 1)
        self.proxyTypeLabel = QtGui.QLabel(self.proxyManualWidget)
        self.proxyTypeLabel.setObjectName(_fromUtf8("proxyTypeLabel"))
        self.gridLayout.addWidget(self.proxyTypeLabel, 0, 0, 1, 1)
        self.proxyType = QtGui.QComboBox(self.proxyManualWidget)
        self.proxyType.setObjectName(_fromUtf8("proxyType"))
        self.proxyType.addItem(_fromUtf8(""))
        self.proxyType.addItem(_fromUtf8(""))
        self.proxyType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.proxyType, 0, 2, 1, 1)
        self.portLabel = QtGui.QLabel(self.proxyManualWidget)
        self.portLabel.setObjectName(_fromUtf8("portLabel"))
        self.gridLayout.addWidget(self.portLabel, 2, 3, 1, 1)
        self.srvLoginLabel = QtGui.QLabel(self.proxyManualWidget)
        self.srvLoginLabel.setObjectName(_fromUtf8("srvLoginLabel"))
        self.gridLayout.addWidget(self.srvLoginLabel, 4, 0, 1, 1)
        self.srvLabel = QtGui.QLabel(self.proxyManualWidget)
        self.srvLabel.setObjectName(_fromUtf8("srvLabel"))
        self.gridLayout.addWidget(self.srvLabel, 2, 0, 1, 1)
        self.srvName = QtGui.QLineEdit(self.proxyManualWidget)
        self.srvName.setObjectName(_fromUtf8("srvName"))
        self.gridLayout.addWidget(self.srvName, 2, 2, 1, 1)
        self.portNumber = QtGui.QLineEdit(self.proxyManualWidget)
        self.portNumber.setMinimumSize(QtCore.QSize(50, 0))
        self.portNumber.setMaximumSize(QtCore.QSize(50, 16777215))
        self.portNumber.setObjectName(_fromUtf8("portNumber"))
        self.gridLayout.addWidget(self.portNumber, 2, 4, 1, 1)
        self.srvPasswordReq = QtGui.QCheckBox(self.proxyManualWidget)
        self.srvPasswordReq.setObjectName(_fromUtf8("srvPasswordReq"))
        self.gridLayout.addWidget(self.srvPasswordReq, 3, 2, 1, 1)
        self.srvPasswordLabel = QtGui.QLabel(self.proxyManualWidget)
        self.srvPasswordLabel.setObjectName(_fromUtf8("srvPasswordLabel"))
        self.gridLayout.addWidget(self.srvPasswordLabel, 5, 0, 1, 1)
        self.srvPassword = QtGui.QLineEdit(self.proxyManualWidget)
        self.srvPassword.setEnabled(False)
        self.srvPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.srvPassword.setObjectName(_fromUtf8("srvPassword"))
        self.gridLayout.addWidget(self.srvPassword, 5, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.proxyManualWidget)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(os.path.realpath(__file__)), "../ico/tab_proxy.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_6)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.startHidden = QtGui.QCheckBox(self.groupBox_6)
        self.startHidden.setObjectName(_fromUtf8("startHidden"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.startHidden)
        self.hideOnMinimize = QtGui.QCheckBox(self.groupBox_6)
        self.hideOnMinimize.setObjectName(_fromUtf8("hideOnMinimize"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.hideOnMinimize)
        self.l_refresh_1 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_refresh_1.sizePolicy().hasHeightForWidth())
        self.l_refresh_1.setSizePolicy(sizePolicy)
        self.l_refresh_1.setObjectName(_fromUtf8("l_refresh_1"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.l_refresh_1)
        self.refreshTimeout = QtGui.QSpinBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshTimeout.sizePolicy().hasHeightForWidth())
        self.refreshTimeout.setSizePolicy(sizePolicy)
        self.refreshTimeout.setMaximum(300)
        self.refreshTimeout.setProperty("value", 15)
        self.refreshTimeout.setObjectName(_fromUtf8("refreshTimeout"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.refreshTimeout)
        self.startServiceAtStart = QtGui.QCheckBox(self.groupBox_6)
        self.startServiceAtStart.setObjectName(_fromUtf8("startServiceAtStart"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.startServiceAtStart)
        self.gridLayout_2.addWidget(self.groupBox_6, 0, 0, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(os.path.realpath(__file__)), "../ico/tab_opts.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_5, icon5, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.ctrFrame = QtGui.QFrame(self.centralwidget)
        self.ctrFrame.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctrFrame.sizePolicy().hasHeightForWidth())
        self.ctrFrame.setSizePolicy(sizePolicy)
        self.ctrFrame.setMinimumSize(QtCore.QSize(250, 50))
        self.ctrFrame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ctrFrame.setAutoFillBackground(True)
        self.ctrFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.ctrFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.ctrFrame.setObjectName(_fromUtf8("ctrFrame"))
        self.hboxlayout = QtGui.QHBoxLayout(self.ctrFrame)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.btnStart = QtGui.QPushButton(self.ctrFrame)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(os.path.realpath(__file__)), "../ico/start.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStart.setIcon(icon6)
        self.btnStart.setObjectName(_fromUtf8("btnStart"))
        self.hboxlayout.addWidget(self.btnStart)
        self.btnStop = QtGui.QPushButton(self.ctrFrame)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(os.path.realpath(__file__)), "../ico/stop.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStop.setIcon(icon7)
        self.btnStop.setObjectName(_fromUtf8("btnStop"))
        self.hboxlayout.addWidget(self.btnStop)
        self.btnStatus = QtGui.QPushButton(self.ctrFrame)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(os.path.realpath(__file__)), "../ico/status.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStatus.setIcon(icon8)
        self.btnStatus.setObjectName(_fromUtf8("btnStatus"))
        self.hboxlayout.addWidget(self.btnStatus)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.btnExit = QtGui.QPushButton(self.ctrFrame)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(os.path.realpath(__file__)), "../ico/exit.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExit.setIcon(icon9)
        self.btnExit.setObjectName(_fromUtf8("btnExit"))
        self.hboxlayout.addWidget(self.btnExit)
        self.verticalLayout.addWidget(self.ctrFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 515, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuService = QtGui.QMenu(self.menubar)
        self.menuService.setObjectName(_fromUtf8("menuService"))
        self.menuCfg = QtGui.QMenu(self.menubar)
        self.menuCfg.setObjectName(_fromUtf8("menuCfg"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuApplication = QtGui.QMenu(self.menubar)
        self.menuApplication.setObjectName(_fromUtf8("menuApplication"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionStart = QtGui.QAction(MainWindow)
        self.actionStart.setIcon(icon6)
        self.actionStart.setObjectName(_fromUtf8("actionStart"))
        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setIcon(icon7)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionStatus = QtGui.QAction(MainWindow)
        self.actionStatus.setIcon(icon8)
        self.actionStatus.setObjectName(_fromUtf8("actionStatus"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setIcon(icon9)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSaveCfg = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(os.path.realpath(__file__)), "../ico/save.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveCfg.setIcon(icon10)
        self.actionSaveCfg.setObjectName(_fromUtf8("actionSaveCfg"))
        self.actionReloadCfg = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(os.path.realpath(__file__)), "../ico/reload.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReloadCfg.setIcon(icon11)
        self.actionReloadCfg.setObjectName(_fromUtf8("actionReloadCfg"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(os.path.realpath(__file__)), "../ico/about.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon12)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionHide = QtGui.QAction(MainWindow)
        self.actionHide.setObjectName(_fromUtf8("actionHide"))
        self.actionSetup_Wizard = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(os.path.realpath(__file__)), "../ico/wizard.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSetup_Wizard.setIcon(icon13)
        self.actionSetup_Wizard.setObjectName(_fromUtf8("actionSetup_Wizard"))
        self.menuService.addAction(self.actionStart)
        self.menuService.addAction(self.actionStop)
        self.menuService.addAction(self.actionStatus)
        self.menuService.addSeparator()
        self.menuCfg.addAction(self.actionSaveCfg)
        self.menuCfg.addAction(self.actionReloadCfg)
        self.menuHelp.addAction(self.actionAbout)
        self.menuApplication.addAction(self.actionSetup_Wizard)
        self.menuApplication.addSeparator()
        self.menuApplication.addAction(self.actionHide)
        self.menuApplication.addAction(self.actionExit)
        self.menubar.addAction(self.menuApplication.menuAction())
        self.menubar.addAction(self.menuService.menuAction())
        self.menubar.addAction(self.menuCfg.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Yandex Disk Service Helper", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Service Status", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Directories to Sync", None))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Sync Dirs", None))
        self.groupBox_1.setTitle(_translate("MainWindow", "yandex-disk executable path", None))
        self.yandex_exec.setToolTip(_translate("MainWindow", "yandex-disk executable path", None))
        self.yandex_exec.setStatusTip(_translate("MainWindow", "yandex-disk executable path", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Configuration file path", None))
        self.yandex_cfg.setToolTip(_translate("MainWindow", "Path to yandex disk configuration file", None))
        self.yandex_cfg.setStatusTip(_translate("MainWindow", "Path to yandex disk configuration file", None))
        self.ch_yandex_cfg.setToolTip(_translate("MainWindow", "Change Yandex Configuration File Path", None))
        self.ch_yandex_cfg.setStatusTip(_translate("MainWindow", "Change Yandex Configuration File Path", None))
        self.ch_yandex_cfg.setText(_translate("MainWindow", "...", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Yandex Disk root directory", None))
        self.yandex_root.setToolTip(_translate("MainWindow", "Root directory for synchronization", None))
        self.yandex_root.setStatusTip(_translate("MainWindow", "Root directory for synchronization", None))
        self.ch_yandex_root.setToolTip(_translate("MainWindow", "Change Yandex Disk Root Directory", None))
        self.ch_yandex_root.setStatusTip(_translate("MainWindow", "Change Yandex Disk Root Directory", None))
        self.ch_yandex_root.setText(_translate("MainWindow", "...", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Yandex Disk auth file path", None))
        self.yandex_auth.setToolTip(_translate("MainWindow", "Yandex Disk authorization file path", None))
        self.yandex_auth.setStatusTip(_translate("MainWindow", "Yandex Disk authorization file path", None))
        self.ch_yandex_auth.setToolTip(_translate("MainWindow", "Change Yandex Authorization File Path", None))
        self.ch_yandex_auth.setStatusTip(_translate("MainWindow", "Change Yandex Authorization File Path", None))
        self.ch_yandex_auth.setText(_translate("MainWindow", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Configuration", None))
        self.proxyNone.setText(_translate("MainWindow", "None", None))
        self.proxyAuto.setText(_translate("MainWindow", "Auto", None))
        self.proxyManual.setText(_translate("MainWindow", "Manual", None))
        self.srvLogin.setToolTip(_translate("MainWindow", "Proxy server login", None))
        self.srvLogin.setStatusTip(_translate("MainWindow", "Proxy server login", None))
        self.proxyTypeLabel.setText(_translate("MainWindow", "Type:", None))
        self.proxyType.setToolTip(_translate("MainWindow", "Proxy type", None))
        self.proxyType.setStatusTip(_translate("MainWindow", "Choose proxy type", None))
        self.proxyType.setItemText(0, _translate("MainWindow", "HTTPS", None))
        self.proxyType.setItemText(1, _translate("MainWindow", "SOCKS4", None))
        self.proxyType.setItemText(2, _translate("MainWindow", "SOCKS5", None))
        self.portLabel.setText(_translate("MainWindow", "Port:", None))
        self.srvLoginLabel.setText(_translate("MainWindow", "Login:", None))
        self.srvLabel.setText(_translate("MainWindow", "Server:", None))
        self.srvName.setToolTip(_translate("MainWindow", "Proxy server", None))
        self.srvName.setStatusTip(_translate("MainWindow", "Proxy server hostname or IP address", None))
        self.portNumber.setToolTip(_translate("MainWindow", "Proxy port", None))
        self.portNumber.setStatusTip(_translate("MainWindow", "Proxy port", None))
        self.srvPasswordReq.setToolTip(_translate("MainWindow", "Proxy server authorization", None))
        self.srvPasswordReq.setStatusTip(_translate("MainWindow", "Proxy server authorization", None))
        self.srvPasswordReq.setText(_translate("MainWindow", "Server Credentials", None))
        self.srvPasswordLabel.setText(_translate("MainWindow", "Password:", None))
        self.srvPassword.setToolTip(_translate("MainWindow", "Proxy server password", None))
        self.srvPassword.setStatusTip(_translate("MainWindow", "Proxy server password", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Proxy", None))
        self.startHidden.setToolTip(_translate("MainWindow", "Start Application Hidden in a System Tray", None))
        self.startHidden.setStatusTip(_translate("MainWindow", "Start Application Hidden in a System Tray", None))
        self.startHidden.setText(_translate("MainWindow", "Start Hidden", None))
        self.hideOnMinimize.setToolTip(_translate("MainWindow", "Remove Application From TaskBar when minimized", None))
        self.hideOnMinimize.setStatusTip(_translate("MainWindow", "Remove Application From TaskBar when minimized", None))
        self.hideOnMinimize.setText(_translate("MainWindow", "Hide On Minimize", None))
        self.l_refresh_1.setText(_translate("MainWindow", "Status autorefresh in sec", None))
        self.refreshTimeout.setToolTip(_translate("MainWindow", "Timeout after which status will be autorefreshed. Zero - no autorefresh", None))
        self.refreshTimeout.setStatusTip(_translate("MainWindow", "Timeout after which status will be autorefreshed. Zero - no autorefresh", None))
        self.startServiceAtStart.setToolTip(_translate("MainWindow", "Start yandex-disk daemon on application start", None))
        self.startServiceAtStart.setStatusTip(_translate("MainWindow", "Start yandex-disk daemon on application start", None))
        self.startServiceAtStart.setText(_translate("MainWindow", "Start Service At Application Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Options", None))
        self.btnStart.setToolTip(_translate("MainWindow", "Start Service", None))
        self.btnStart.setStatusTip(_translate("MainWindow", "Start Service", None))
        self.btnStart.setText(_translate("MainWindow", "Start", None))
        self.btnStop.setToolTip(_translate("MainWindow", "Stop Service", None))
        self.btnStop.setStatusTip(_translate("MainWindow", "Stop Service", None))
        self.btnStop.setText(_translate("MainWindow", "Stop", None))
        self.btnStatus.setToolTip(_translate("MainWindow", "Check Service Status", None))
        self.btnStatus.setStatusTip(_translate("MainWindow", "Check Service Status", None))
        self.btnStatus.setText(_translate("MainWindow", "Status", None))
        self.btnExit.setToolTip(_translate("MainWindow", "Exit Application", None))
        self.btnExit.setStatusTip(_translate("MainWindow", "Exit Application", None))
        self.btnExit.setText(_translate("MainWindow", "Exit", None))
        self.menuService.setTitle(_translate("MainWindow", "&Service", None))
        self.menuCfg.setTitle(_translate("MainWindow", "&Configuration", None))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help", None))
        self.menuApplication.setTitle(_translate("MainWindow", "&Application", None))
        self.actionStart.setText(_translate("MainWindow", "&Start", None))
        self.actionStart.setStatusTip(_translate("MainWindow", "Start Service", None))
        self.actionStop.setText(_translate("MainWindow", "Sto&p", None))
        self.actionStop.setStatusTip(_translate("MainWindow", "Stop Service", None))
        self.actionStatus.setText(_translate("MainWindow", "S&tatus", None))
        self.actionStatus.setStatusTip(_translate("MainWindow", "Check Service Status", None))
        self.actionExit.setText(_translate("MainWindow", "E&xit", None))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit Application", None))
        self.actionSaveCfg.setText(_translate("MainWindow", "&Save", None))
        self.actionSaveCfg.setStatusTip(_translate("MainWindow", "Save Current Configuration", None))
        self.actionReloadCfg.setText(_translate("MainWindow", "&Reload", None))
        self.actionReloadCfg.setStatusTip(_translate("MainWindow", "Reload Configuration From Config File(s)", None))
        self.actionAbout.setText(_translate("MainWindow", "&About", None))
        self.actionAbout.setStatusTip(_translate("MainWindow", "About Application", None))
        self.actionHide.setText(_translate("MainWindow", "&Hide", None))
        self.actionSetup_Wizard.setText(_translate("MainWindow", "Setup &Wizard", None))

